export function queryStudioWorkspaceElements(root: HTMLElement) {
  const query = <T extends Element>(selector: string) => root.querySelector<T>(selector)!
  return {
    workspaceStatus: query<HTMLElement>('#workspace-status'),
    environmentPreset: query<HTMLSelectElement>('#environment-preset'),
    fontTheme: query<HTMLSelectElement>('#font-theme'),
    motion: query<HTMLButtonElement>('#motion'),
    galleryToggle: query<HTMLButtonElement>('#gallery-toggle'),
    scale: query<HTMLButtonElement>('#scale'),
    play: query<HTMLButtonElement>('#play'),
    audienceOpen: query<HTMLButtonElement>('#audience-open'),
    speakerOpen: query<HTMLButtonElement>('#speaker-open'),
    presentationOpen: query<HTMLButtonElement>('#presentation-open'),
    presentationEnd: query<HTMLButtonElement>('#presentation-end'),
    sessionStatus: query<HTMLOutputElement>('#presentation-session-status'),
    audienceStatus: query<HTMLElement>('[data-audience-status]'),
    presenterStatus: query<HTMLElement>('[data-presenter-status]'),
    notesWorkspace: query<HTMLElement>('.notes-workspace'),
    notesTextarea: query<HTMLTextAreaElement>('#notes-textarea'),
    notesSlideLabel: query<HTMLElement>('#notes-slide-label'),
    notesStatus: query<HTMLElement>('#notes-status'),
    stage: query<HTMLElement>('[data-testid="studio-stage"]'),
    canvasViewport: query<HTMLElement>('.studio-canvas-viewport'),
    canvasTransform: query<HTMLElement>('.studio-canvas-transform'),
    rail: query<HTMLElement>('[data-testid="studio-rail"]'),
    railToggle: query<HTMLButtonElement>('#rail-toggle'),
    drawer: query<HTMLElement>('[data-testid="studio-drawer"]'),
    drawerResizeHandle: query<HTMLElement>('[data-drawer-resize-handle]'),
    drawerTabs: [...root.querySelectorAll<HTMLButtonElement>('[data-drawer-panel]')],
    zoomValue: query<HTMLOutputElement>('#zoom-value'),
    zoomSlider: query<HTMLInputElement>('#zoom-slider'),
    slideCount: query<HTMLElement>('[data-testid="studio-slide-count"]'),
    fullscreenStatus: query<HTMLElement>('#fullscreen-status'),
    stageFullscreen: query<HTMLButtonElement>('#stage-fullscreen'),
    layoutSelect: query<HTMLSelectElement>('#slide-layout-select'),
    placeholderList: query<HTMLElement>('#placeholder-visibility-list'),
    reapplyLayoutButton: query<HTMLButtonElement>('#reapply-layout'),
    layoutInspectorStatus: query<HTMLOutputElement>('#layout-inspector-status'),
    inspectToggle: query<HTMLButtonElement>('#inspect-toggle'),
    editQueueToggle: query<HTMLButtonElement>('#edit-queue-toggle'),
    editCount: query<HTMLElement>('#studio-edit-count'),
    editList: query<HTMLElement>('#studio-edit-list'),
    editEmpty: query<HTMLElement>('#studio-edit-empty'),
    editStatus: query<HTMLOutputElement>('#studio-edit-status'),
    copyEditPrompt: query<HTMLButtonElement>('#copy-edit-prompt'),
    clearEditQueue: query<HTMLButtonElement>('#clear-edit-queue'),
  }
}

export type StudioWorkspaceElements = ReturnType<typeof queryStudioWorkspaceElements>
