// Generated by scripts/build-visual-assets.mjs from lucide-static@1.31.0. Do not edit.
export const generatedLucideIcons = [
  {
    "name": "message-circle",
    "label": "Message Circle",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "circle"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719\" /></g>"
  },
  {
    "name": "messages-square",
    "label": "Messages Square",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "messages",
      "square"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z\" />\n  <path d=\"M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1\" /></g>"
  },
  {
    "name": "mail",
    "label": "Mail",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "mail"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7\" />\n  <rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\" /></g>"
  },
  {
    "name": "phone-call",
    "label": "Phone Call",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "phone",
      "call"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 2a9 9 0 0 1 9 9\" />\n  <path d=\"M13 6a5 5 0 0 1 5 5\" />\n  <path d=\"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384\" /></g>"
  },
  {
    "name": "screen-share",
    "label": "Screen Share",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "screen",
      "share"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13 3H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-3\" />\n  <path d=\"M8 21h8\" />\n  <path d=\"M12 17v4\" />\n  <path d=\"m17 8 5-5\" />\n  <path d=\"M17 3h5v5\" /></g>"
  },
  {
    "name": "mic",
    "label": "Mic",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "mic"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 19v3\" />\n  <path d=\"M19 10v2a7 7 0 0 1-14 0v-2\" />\n  <rect x=\"9\" y=\"2\" width=\"6\" height=\"13\" rx=\"3\" /></g>"
  },
  {
    "name": "megaphone",
    "label": "Megaphone",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "megaphone"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z\" />\n  <path d=\"M6 14a12 12 0 0 0 2.4 7.2 2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14\" />\n  <path d=\"M8 6v8\" /></g>"
  },
  {
    "name": "radio",
    "label": "Radio",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "radio"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16.247 7.761a6 6 0 0 1 0 8.478\" />\n  <path d=\"M19.075 4.933a10 10 0 0 1 0 14.134\" />\n  <path d=\"M4.925 19.067a10 10 0 0 1 0-14.134\" />\n  <path d=\"M7.753 16.239a6 6 0 0 1 0-8.478\" />\n  <circle cx=\"12\" cy=\"12\" r=\"2\" /></g>"
  },
  {
    "name": "message-square-more",
    "label": "Message Square More",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "square",
      "more"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z\" />\n  <path d=\"M12 11h.01\" />\n  <path d=\"M16 11h.01\" />\n  <path d=\"M8 11h.01\" /></g>"
  },
  {
    "name": "users",
    "label": "Users",
    "group": "communication",
    "groupLabel": "沟通协作",
    "aliases": [
      "communication",
      "collaboration",
      "message",
      "沟通",
      "协作",
      "users"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" />\n  <path d=\"M16 3.128a4 4 0 0 1 0 7.744\" />\n  <path d=\"M22 21v-2a4 4 0 0 0-3-3.87\" />\n  <circle cx=\"9\" cy=\"7\" r=\"4\" /></g>"
  },
  {
    "name": "plus",
    "label": "Plus",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 12h14\" />\n  <path d=\"M12 5v14\" /></g>"
  },
  {
    "name": "circle-plus",
    "label": "Circle Plus",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "circle",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M8 12h8\" />\n  <path d=\"M12 8v8\" /></g>"
  },
  {
    "name": "pencil",
    "label": "Pencil",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "pencil"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z\" />\n  <path d=\"m15 5 4 4\" /></g>"
  },
  {
    "name": "notebook-pen",
    "label": "Notebook Pen",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "notebook",
      "pen"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13.4 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7.4\" />\n  <path d=\"M2 6h4\" />\n  <path d=\"M2 10h4\" />\n  <path d=\"M2 14h4\" />\n  <path d=\"M2 18h4\" />\n  <path d=\"M21.378 5.626a1 1 0 1 0-3.004-3.004l-5.01 5.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" /></g>"
  },
  {
    "name": "wand-sparkles",
    "label": "Wand Sparkles",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "wand",
      "sparkles"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72\" />\n  <path d=\"m14 7 3 3\" />\n  <path d=\"M5 6v4\" />\n  <path d=\"M19 14v4\" />\n  <path d=\"M10 2v2\" />\n  <path d=\"M7 8H3\" />\n  <path d=\"M21 16h-4\" />\n  <path d=\"M11 3H9\" /></g>"
  },
  {
    "name": "sparkles",
    "label": "Sparkles",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "sparkles"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z\" />\n  <path d=\"M20 2v4\" />\n  <path d=\"M22 4h-4\" />\n  <circle cx=\"4\" cy=\"20\" r=\"2\" /></g>"
  },
  {
    "name": "image-plus",
    "label": "Image Plus",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "image",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 5h6\" />\n  <path d=\"M19 2v6\" />\n  <path d=\"M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5\" />\n  <path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" />\n  <circle cx=\"9\" cy=\"9\" r=\"2\" /></g>"
  },
  {
    "name": "file-plus",
    "label": "File Plus",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "file",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M9 15h6\" />\n  <path d=\"M12 18v-6\" /></g>"
  },
  {
    "name": "folder-plus",
    "label": "Folder Plus",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "folder",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 10v6\" />\n  <path d=\"M9 13h6\" />\n  <path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" /></g>"
  },
  {
    "name": "paintbrush",
    "label": "Paintbrush",
    "group": "creation",
    "groupLabel": "创建编辑",
    "aliases": [
      "create",
      "add",
      "edit",
      "author",
      "创建",
      "编辑",
      "paintbrush"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m14.622 17.897-10.68-2.913\" />\n  <path d=\"M18.376 2.622a1 1 0 1 1 3.002 3.002L17.36 9.643a.5.5 0 0 0 0 .707l.944.944a2.41 2.41 0 0 1 0 3.408l-.944.944a.5.5 0 0 1-.707 0L8.354 7.348a.5.5 0 0 1 0-.707l.944-.944a2.41 2.41 0 0 1 3.408 0l.944.944a.5.5 0 0 0 .707 0z\" />\n  <path d=\"M9 8c-1.804 2.71-3.97 3.46-6.583 3.948a.507.507 0 0 0-.302.819l7.32 8.883a1 1 0 0 0 1.185.204C12.735 20.405 16 16.792 16 15\" /></g>"
  },
  {
    "name": "search",
    "label": "Search",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m21 21-4.34-4.34\" />\n  <circle cx=\"11\" cy=\"11\" r=\"8\" /></g>"
  },
  {
    "name": "zoom-in",
    "label": "Zoom In",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "zoom",
      "in"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"11\" cy=\"11\" r=\"8\" />\n  <line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" />\n  <line x1=\"11\" x2=\"11\" y1=\"8\" y2=\"14\" />\n  <line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" /></g>"
  },
  {
    "name": "zoom-out",
    "label": "Zoom Out",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "zoom",
      "out"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"11\" cy=\"11\" r=\"8\" />\n  <line x1=\"21\" x2=\"16.65\" y1=\"21\" y2=\"16.65\" />\n  <line x1=\"8\" x2=\"14\" y1=\"11\" y2=\"11\" /></g>"
  },
  {
    "name": "file-search",
    "label": "File Search",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "file"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <circle cx=\"11.5\" cy=\"14.5\" r=\"2.5\" />\n  <path d=\"M13.3 16.3 15 18\" /></g>"
  },
  {
    "name": "list-filter",
    "label": "List Filter",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "list"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 5h20\" />\n  <path d=\"M6 12h12\" />\n  <path d=\"M9 19h6\" /></g>"
  },
  {
    "name": "eye",
    "label": "Eye",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "eye"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0\" />\n  <circle cx=\"12\" cy=\"12\" r=\"3\" /></g>"
  },
  {
    "name": "target",
    "label": "Target",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "target"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <circle cx=\"12\" cy=\"12\" r=\"6\" />\n  <circle cx=\"12\" cy=\"12\" r=\"2\" /></g>"
  },
  {
    "name": "filter",
    "label": "Filter",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z\" /></g>"
  },
  {
    "name": "compass",
    "label": "Compass",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "compass"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z\" /></g>"
  },
  {
    "name": "binoculars",
    "label": "Binoculars",
    "group": "discovery",
    "groupLabel": "搜索发现",
    "aliases": [
      "search",
      "discover",
      "focus",
      "filter",
      "搜索",
      "发现",
      "binoculars"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 10h4\" />\n  <path d=\"M19 7V4a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v3\" />\n  <path d=\"M20 21a2 2 0 0 0 2-2v-3.851c0-1.39-2-2.962-2-4.829V8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v11a2 2 0 0 0 2 2z\" />\n  <path d=\"M 22 16 L 2 16\" />\n  <path d=\"M4 21a2 2 0 0 1-2-2v-3.851c0-1.39 2-2.962 2-4.829V8a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v11a2 2 0 0 1-2 2z\" />\n  <path d=\"M9 7V4a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v3\" /></g>"
  },
  {
    "name": "chart-bar",
    "label": "Chart Bar",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "bar"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <path d=\"M7 16h8\" />\n  <path d=\"M7 11h12\" />\n  <path d=\"M7 6h3\" /></g>"
  },
  {
    "name": "chart-line",
    "label": "Chart Line",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "line"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <path d=\"m19 9-5 5-4-4-3 3\" /></g>"
  },
  {
    "name": "chart-no-axes-combined",
    "label": "Chart No Axes Combined",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "no",
      "axes",
      "combined"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 16v5\" />\n  <path d=\"M16 14.639V21\" />\n  <path d=\"M20 10.656V21\" />\n  <path d=\"m22 3-8.646 8.646a.5.5 0 0 1-.708 0L9.354 8.354a.5.5 0 0 0-.707 0L2 15\" />\n  <path d=\"M4 18.463V21\" />\n  <path d=\"M8 14.656V21\" /></g>"
  },
  {
    "name": "chart-pie",
    "label": "Chart Pie",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "pie"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z\" />\n  <path d=\"M21.21 15.89A10 10 0 1 1 8 2.83\" /></g>"
  },
  {
    "name": "chart-scatter",
    "label": "Chart Scatter",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "scatter"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />\n  <circle cx=\"18.5\" cy=\"5.5\" r=\".5\" fill=\"currentColor\" />\n  <circle cx=\"11.5\" cy=\"11.5\" r=\".5\" fill=\"currentColor\" />\n  <circle cx=\"7.5\" cy=\"16.5\" r=\".5\" fill=\"currentColor\" />\n  <circle cx=\"17.5\" cy=\"14.5\" r=\".5\" fill=\"currentColor\" />\n  <path d=\"M3 3v16a2 2 0 0 0 2 2h16\" /></g>"
  },
  {
    "name": "chart-network",
    "label": "Chart Network",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "chart",
      "network"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m13.11 7.664 1.78 2.672\" />\n  <path d=\"m14.162 12.788-3.324 1.424\" />\n  <path d=\"m20 4-6.06 1.515\" />\n  <path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <circle cx=\"12\" cy=\"6\" r=\"2\" />\n  <circle cx=\"16\" cy=\"12\" r=\"2\" />\n  <circle cx=\"9\" cy=\"15\" r=\"2\" /></g>"
  },
  {
    "name": "database",
    "label": "Database",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "database"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><ellipse cx=\"12\" cy=\"5\" rx=\"9\" ry=\"3\" />\n  <path d=\"M3 5V19A9 3 0 0 0 21 19V5\" />\n  <path d=\"M3 12A9 3 0 0 0 21 12\" /></g>"
  },
  {
    "name": "table",
    "label": "Table",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "table"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3v18\" />\n  <rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M3 9h18\" />\n  <path d=\"M3 15h18\" /></g>"
  },
  {
    "name": "trending-up",
    "label": "Trending Up",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "trending",
      "up"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 7h6v6\" />\n  <path d=\"m22 7-8.5 8.5-5-5L2 17\" /></g>"
  },
  {
    "name": "trending-down",
    "label": "Trending Down",
    "group": "data",
    "groupLabel": "数据分析",
    "aliases": [
      "data",
      "analytics",
      "metric",
      "growth",
      "数据",
      "增长",
      "trending",
      "down"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 17h6v-6\" />\n  <path d=\"m22 17-8.5-8.5-5 5L2 7\" /></g>"
  },
  {
    "name": "cpu",
    "label": "Cpu",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "cpu"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 20v2\" />\n  <path d=\"M12 2v2\" />\n  <path d=\"M17 20v2\" />\n  <path d=\"M17 2v2\" />\n  <path d=\"M2 12h2\" />\n  <path d=\"M2 17h2\" />\n  <path d=\"M2 7h2\" />\n  <path d=\"M20 12h2\" />\n  <path d=\"M20 17h2\" />\n  <path d=\"M20 7h2\" />\n  <path d=\"M7 20v2\" />\n  <path d=\"M7 2v2\" />\n  <rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" />\n  <rect x=\"8\" y=\"8\" width=\"8\" height=\"8\" rx=\"1\" /></g>"
  },
  {
    "name": "circuit-board",
    "label": "Circuit Board",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "circuit",
      "board"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M11 9h4a2 2 0 0 0 2-2V3\" />\n  <circle cx=\"9\" cy=\"9\" r=\"2\" />\n  <path d=\"M7 21v-4a2 2 0 0 1 2-2h4\" />\n  <circle cx=\"15\" cy=\"15\" r=\"2\" /></g>"
  },
  {
    "name": "terminal",
    "label": "Terminal",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "terminal"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 19h8\" />\n  <path d=\"m4 17 6-6-6-6\" /></g>"
  },
  {
    "name": "square-terminal",
    "label": "Square Terminal",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "square",
      "terminal"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m7 11 2-2-2-2\" />\n  <path d=\"M11 13h4\" />\n  <rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" /></g>"
  },
  {
    "name": "code-xml",
    "label": "Code Xml",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "code",
      "xml"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m18 16 4-4-4-4\" />\n  <path d=\"m6 8-4 4 4 4\" />\n  <path d=\"m14.5 4-5 16\" /></g>"
  },
  {
    "name": "braces",
    "label": "Braces",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "braces"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5c0 1.1.9 2 2 2h1\" />\n  <path d=\"M16 21h1a2 2 0 0 0 2-2v-5c0-1.1.9-2 2-2a2 2 0 0 1-2-2V5a2 2 0 0 0-2-2h-1\" /></g>"
  },
  {
    "name": "monitor",
    "label": "Monitor",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "monitor"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" />\n  <line x1=\"8\" x2=\"16\" y1=\"21\" y2=\"21\" />\n  <line x1=\"12\" x2=\"12\" y1=\"17\" y2=\"21\" /></g>"
  },
  {
    "name": "smartphone",
    "label": "Smartphone",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "smartphone"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" />\n  <path d=\"M12 18h.01\" /></g>"
  },
  {
    "name": "server",
    "label": "Server",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "server"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"20\" height=\"8\" x=\"2\" y=\"2\" rx=\"2\" ry=\"2\" />\n  <rect width=\"20\" height=\"8\" x=\"2\" y=\"14\" rx=\"2\" ry=\"2\" />\n  <line x1=\"6\" x2=\"6.01\" y1=\"6\" y2=\"6\" />\n  <line x1=\"6\" x2=\"6.01\" y1=\"18\" y2=\"18\" /></g>"
  },
  {
    "name": "binary",
    "label": "Binary",
    "group": "technology",
    "groupLabel": "技术系统",
    "aliases": [
      "technology",
      "system",
      "development",
      "architecture",
      "技术",
      "架构",
      "binary"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"14\" y=\"14\" width=\"4\" height=\"6\" rx=\"2\" />\n  <rect x=\"6\" y=\"4\" width=\"4\" height=\"6\" rx=\"2\" />\n  <path d=\"M6 20h4\" />\n  <path d=\"M14 10h4\" />\n  <path d=\"M6 14h2v6\" />\n  <path d=\"M14 4h2v6\" /></g>"
  },
  {
    "name": "brain",
    "label": "Brain",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "brain"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 18V5\" />\n  <path d=\"M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4\" />\n  <path d=\"M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5\" />\n  <path d=\"M17.997 5.125a4 4 0 0 1 2.526 5.77\" />\n  <path d=\"M18 18a4 4 0 0 0 2-7.464\" />\n  <path d=\"M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517\" />\n  <path d=\"M6 18a4 4 0 0 1-2-7.464\" />\n  <path d=\"M6.003 5.125a4 4 0 0 0-2.526 5.77\" /></g>"
  },
  {
    "name": "bot",
    "label": "Bot",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "bot"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 8V4H8\" />\n  <rect width=\"16\" height=\"12\" x=\"4\" y=\"8\" rx=\"2\" />\n  <path d=\"M2 14h2\" />\n  <path d=\"M20 14h2\" />\n  <path d=\"M15 13v2\" />\n  <path d=\"M9 13v2\" /></g>"
  },
  {
    "name": "brain-circuit",
    "label": "Brain Circuit",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "brain",
      "circuit"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z\" />\n  <path d=\"M9 13a4.5 4.5 0 0 0 3-4\" />\n  <path d=\"M6.003 5.125A3 3 0 0 0 6.401 6.5\" />\n  <path d=\"M3.477 10.896a4 4 0 0 1 .585-.396\" />\n  <path d=\"M6 18a4 4 0 0 1-1.967-.516\" />\n  <path d=\"M12 13h4\" />\n  <path d=\"M12 18h6a2 2 0 0 1 2 2v1\" />\n  <path d=\"M12 8h8\" />\n  <path d=\"M16 8V5a2 2 0 0 1 2-2\" />\n  <circle cx=\"16\" cy=\"13\" r=\".5\" />\n  <circle cx=\"18\" cy=\"3\" r=\".5\" />\n  <circle cx=\"20\" cy=\"21\" r=\".5\" />\n  <circle cx=\"20\" cy=\"8\" r=\".5\" /></g>"
  },
  {
    "name": "atom",
    "label": "Atom",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "atom"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"1\" />\n  <path d=\"M20.2 20.2c2.04-2.03.02-7.36-4.5-11.9-4.54-4.52-9.87-6.54-11.9-4.5-2.04 2.03-.02 7.36 4.5 11.9 4.54 4.52 9.87 6.54 11.9 4.5Z\" />\n  <path d=\"M15.7 15.7c4.52-4.54 6.54-9.87 4.5-11.9-2.03-2.04-7.36-.02-11.9 4.5-4.52 4.54-6.54 9.87-4.5 11.9 2.03 2.04 7.36.02 11.9-4.5Z\" /></g>"
  },
  {
    "name": "bot-message-square",
    "label": "Bot Message Square",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "bot",
      "message",
      "square"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 6V2H8\" />\n  <path d=\"M15 11v2\" />\n  <path d=\"M2 12h2\" />\n  <path d=\"M20 12h2\" />\n  <path d=\"M20 16a2 2 0 0 1-2 2H8.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 4 20.286V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2z\" />\n  <path d=\"M9 11v2\" /></g>"
  },
  {
    "name": "scan-search",
    "label": "Scan Search",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "scan",
      "search"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 7V5a2 2 0 0 1 2-2h2\" />\n  <path d=\"M17 3h2a2 2 0 0 1 2 2v2\" />\n  <path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" />\n  <path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" />\n  <circle cx=\"12\" cy=\"12\" r=\"3\" />\n  <path d=\"m16 16-1.9-1.9\" /></g>"
  },
  {
    "name": "zap",
    "label": "Zap",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "zap"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z\" /></g>"
  },
  {
    "name": "audio-waveform",
    "label": "Audio Waveform",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "audio",
      "waveform"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 13a2 2 0 0 0 2-2V7a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0V4a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0v-4a2 2 0 0 1 2-2\" /></g>"
  },
  {
    "name": "activity",
    "label": "Activity",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "activity"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\" /></g>"
  },
  {
    "name": "orbit",
    "label": "Orbit",
    "group": "ai",
    "groupLabel": "AI 智能",
    "aliases": [
      "ai",
      "intelligence",
      "thinking",
      "automation",
      "人工智能",
      "智能",
      "orbit"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.341 6.484A10 10 0 0 1 10.266 21.85\" />\n  <path d=\"M3.659 17.516A10 10 0 0 1 13.74 2.152\" />\n  <circle cx=\"12\" cy=\"12\" r=\"3\" />\n  <circle cx=\"19\" cy=\"5\" r=\"2\" />\n  <circle cx=\"5\" cy=\"19\" r=\"2\" /></g>"
  },
  {
    "name": "refresh-cw",
    "label": "Refresh Cw",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "refresh",
      "cw"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\" />\n  <path d=\"M21 3v5h-5\" />\n  <path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\" />\n  <path d=\"M8 16H3v5\" /></g>"
  },
  {
    "name": "workflow",
    "label": "Workflow",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"8\" height=\"8\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M7 11v4a2 2 0 0 0 2 2h4\" />\n  <rect width=\"8\" height=\"8\" x=\"13\" y=\"13\" rx=\"2\" /></g>"
  },
  {
    "name": "route",
    "label": "Route",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "route"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"6\" cy=\"19\" r=\"3\" />\n  <path d=\"M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15\" />\n  <circle cx=\"18\" cy=\"5\" r=\"3\" /></g>"
  },
  {
    "name": "layers",
    "label": "Layers",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "layers"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z\" />\n  <path d=\"M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12\" />\n  <path d=\"M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17\" /></g>"
  },
  {
    "name": "rows-3",
    "label": "Rows 3",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "rows",
      "3"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M21 9H3\" />\n  <path d=\"M21 15H3\" /></g>"
  },
  {
    "name": "columns-3",
    "label": "Columns 3",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "columns",
      "3"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M9 3v18\" />\n  <path d=\"M15 3v18\" /></g>"
  },
  {
    "name": "grid-3x3",
    "label": "Grid 3x3",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "grid",
      "3x3"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M3 9h18\" />\n  <path d=\"M3 15h18\" />\n  <path d=\"M9 3v18\" />\n  <path d=\"M15 3v18\" /></g>"
  },
  {
    "name": "list-ordered",
    "label": "List Ordered",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "list",
      "ordered"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M11 5h10\" />\n  <path d=\"M11 12h10\" />\n  <path d=\"M11 19h10\" />\n  <path d=\"M4 4h1v5\" />\n  <path d=\"M4 9h2\" />\n  <path d=\"M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02\" /></g>"
  },
  {
    "name": "network",
    "label": "Network",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "network"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"16\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" />\n  <rect x=\"2\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" />\n  <rect x=\"9\" y=\"2\" width=\"6\" height=\"6\" rx=\"1\" />\n  <path d=\"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3\" />\n  <path d=\"M12 12V8\" /></g>"
  },
  {
    "name": "git-merge",
    "label": "Git Merge",
    "group": "process",
    "groupLabel": "流程编排",
    "aliases": [
      "process",
      "workflow",
      "orchestration",
      "sequence",
      "流程",
      "编排",
      "git",
      "merge"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"18\" cy=\"18\" r=\"3\" />\n  <circle cx=\"6\" cy=\"6\" r=\"3\" />\n  <path d=\"M6 21V9a9 9 0 0 0 9 9\" /></g>"
  },
  {
    "name": "check",
    "label": "Check",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 6 9 17l-5-5\" /></g>"
  },
  {
    "name": "circle-check",
    "label": "Circle Check",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "circle",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"m9 12 2 2 4-4\" /></g>"
  },
  {
    "name": "badge-check",
    "label": "Badge Check",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "badge",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" />\n  <path d=\"m9 12 2 2 4-4\" /></g>"
  },
  {
    "name": "triangle-alert",
    "label": "Triangle Alert",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "triangle",
      "alert"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" />\n  <path d=\"M12 9v4\" />\n  <path d=\"M12 17h.01\" /></g>"
  },
  {
    "name": "circle-alert",
    "label": "Circle Alert",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "circle",
      "alert"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" />\n  <line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" /></g>"
  },
  {
    "name": "info",
    "label": "Info",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "info"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M12 16v-4\" />\n  <path d=\"M12 8h.01\" /></g>"
  },
  {
    "name": "circle-help",
    "label": "Circle Help",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "circle",
      "help"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3\" />\n  <path d=\"M12 17h.01\" /></g>"
  },
  {
    "name": "circle-x",
    "label": "Circle X",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "circle",
      "x"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"m15 9-6 6\" />\n  <path d=\"m9 9 6 6\" /></g>"
  },
  {
    "name": "circle-check-big",
    "label": "Circle Check Big",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "circle",
      "check",
      "big"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21.801 10A10 10 0 1 1 17 3.335\" />\n  <path d=\"m9 11 3 3L22 4\" /></g>"
  },
  {
    "name": "badge-alert",
    "label": "Badge Alert",
    "group": "status",
    "groupLabel": "状态反馈",
    "aliases": [
      "status",
      "feedback",
      "success",
      "warning",
      "状态",
      "成功",
      "警告",
      "badge",
      "alert"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" />\n  <line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" />\n  <line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" /></g>"
  },
  {
    "name": "lock",
    "label": "Lock",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "lock"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\" />\n  <path d=\"M7 11V7a5 5 0 0 1 10 0v4\" /></g>"
  },
  {
    "name": "lock-open",
    "label": "Lock Open",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "lock",
      "open"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\" />\n  <path d=\"M7 11V7a5 5 0 0 1 9.9-1\" /></g>"
  },
  {
    "name": "key-round",
    "label": "Key Round",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "key",
      "round"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z\" />\n  <circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" /></g>"
  },
  {
    "name": "key-square",
    "label": "Key Square",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "key",
      "square"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.4 2.7a2.5 2.5 0 0 1 3.4 0l5.5 5.5a2.5 2.5 0 0 1 0 3.4l-3.7 3.7a2.5 2.5 0 0 1-3.4 0L8.7 9.8a2.5 2.5 0 0 1 0-3.4z\" />\n  <path d=\"m14 7 3 3\" />\n  <path d=\"m9.4 10.6-6.814 6.814A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814\" /></g>"
  },
  {
    "name": "shield",
    "label": "Shield",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "shield"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" /></g>"
  },
  {
    "name": "shield-check",
    "label": "Shield Check",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "shield",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" />\n  <path d=\"m9 12 2 2 4-4\" /></g>"
  },
  {
    "name": "shield-alert",
    "label": "Shield Alert",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "shield",
      "alert"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z\" />\n  <path d=\"M12 8v4\" />\n  <path d=\"M12 16h.01\" /></g>"
  },
  {
    "name": "fingerprint",
    "label": "Fingerprint",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "fingerprint"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4\" />\n  <path d=\"M14 13.12c0 2.38 0 6.38-1 8.88\" />\n  <path d=\"M17.29 21.02c.12-.6.43-2.3.5-3.02\" />\n  <path d=\"M2 12a10 10 0 0 1 18-6\" />\n  <path d=\"M2 16h.01\" />\n  <path d=\"M21.8 16c.2-2 .131-5.354 0-6\" />\n  <path d=\"M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2\" />\n  <path d=\"M8.65 22c.21-.66.45-1.32.57-2\" />\n  <path d=\"M9 6.8a6 6 0 0 1 9 5.2v2\" /></g>"
  },
  {
    "name": "eye-off",
    "label": "Eye Off",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "eye",
      "off"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49\" />\n  <path d=\"M14.084 14.158a3 3 0 0 1-4.242-4.242\" />\n  <path d=\"M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143\" />\n  <path d=\"m2 2 20 20\" /></g>"
  },
  {
    "name": "scan-face",
    "label": "Scan Face",
    "group": "security",
    "groupLabel": "安全治理",
    "aliases": [
      "security",
      "privacy",
      "governance",
      "risk",
      "安全",
      "风险",
      "scan",
      "face"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 7V5a2 2 0 0 1 2-2h2\" />\n  <path d=\"M17 3h2a2 2 0 0 1 2 2v2\" />\n  <path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" />\n  <path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" />\n  <path d=\"M8 14s1.5 2 4 2 4-2 4-2\" />\n  <path d=\"M9 9h.01\" />\n  <path d=\"M15 9h.01\" /></g>"
  },
  {
    "name": "file",
    "label": "File",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" /></g>"
  },
  {
    "name": "files",
    "label": "Files",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "files"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 2h-4a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8\" />\n  <path d=\"M16.706 2.706A2.4 2.4 0 0 0 15 2v5a1 1 0 0 0 1 1h5a2.4 2.4 0 0 0-.706-1.706z\" />\n  <path d=\"M5 7a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h8a2 2 0 0 0 1.732-1\" /></g>"
  },
  {
    "name": "folder",
    "label": "Folder",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "folder"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z\" /></g>"
  },
  {
    "name": "folders",
    "label": "Folders",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "folders"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20 5a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h2.5a1.5 1.5 0 0 1 1.2.6l.6.8a1.5 1.5 0 0 0 1.2.6z\" />\n  <path d=\"M3 8.268a2 2 0 0 0-1 1.738V19a2 2 0 0 0 2 2h11a2 2 0 0 0 1.732-1\" /></g>"
  },
  {
    "name": "file-text",
    "label": "File Text",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "text"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M10 9H8\" />\n  <path d=\"M16 13H8\" />\n  <path d=\"M16 17H8\" /></g>"
  },
  {
    "name": "file-chart-column",
    "label": "File Chart Column",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "chart",
      "column"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M8 18v-1\" />\n  <path d=\"M12 18v-6\" />\n  <path d=\"M16 18v-3\" /></g>"
  },
  {
    "name": "file-sliders",
    "label": "File Sliders",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "sliders"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M8 12h8\" />\n  <path d=\"M10 11v2\" />\n  <path d=\"M8 17h8\" />\n  <path d=\"M14 16v2\" /></g>"
  },
  {
    "name": "file-spreadsheet",
    "label": "File Spreadsheet",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "spreadsheet"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M8 13h2\" />\n  <path d=\"M14 13h2\" />\n  <path d=\"M8 17h2\" />\n  <path d=\"M14 17h2\" /></g>"
  },
  {
    "name": "file-image",
    "label": "File Image",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "image"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <circle cx=\"10\" cy=\"12\" r=\"2\" />\n  <path d=\"m20 17-1.296-1.296a2.41 2.41 0 0 0-3.408 0L9 22\" /></g>"
  },
  {
    "name": "file-archive",
    "label": "File Archive",
    "group": "documents",
    "groupLabel": "文档知识",
    "aliases": [
      "document",
      "file",
      "knowledge",
      "content",
      "文档",
      "知识",
      "archive"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13.659 22H18a2 2 0 0 0 2-2V8a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 14 2H6a2 2 0 0 0-2 2v11.5\" />\n  <path d=\"M14 2v5a1 1 0 0 0 1 1h5\" />\n  <path d=\"M8 12v-1\" />\n  <path d=\"M8 18v-2\" />\n  <path d=\"M8 7V6\" />\n  <circle cx=\"8\" cy=\"20\" r=\"2\" /></g>"
  },
  {
    "name": "cloud",
    "label": "Cloud",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z\" /></g>"
  },
  {
    "name": "cloud-upload",
    "label": "Cloud Upload",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 13v8\" />\n  <path d=\"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242\" />\n  <path d=\"m8 17 4-4 4 4\" /></g>"
  },
  {
    "name": "cloud-download",
    "label": "Cloud Download",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 13v8l-4-4\" />\n  <path d=\"m12 21 4-4\" />\n  <path d=\"M4.393 15.269A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.436 8.284\" /></g>"
  },
  {
    "name": "upload",
    "label": "Upload",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3v12\" />\n  <path d=\"m17 8-5-5-5 5\" />\n  <path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\" /></g>"
  },
  {
    "name": "download",
    "label": "Download",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 15V3\" />\n  <path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\" />\n  <path d=\"m7 10 5 5 5-5\" /></g>"
  },
  {
    "name": "wifi",
    "label": "Wifi",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接",
      "wifi"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 20h.01\" />\n  <path d=\"M2 8.82a15 15 0 0 1 20 0\" />\n  <path d=\"M5 12.859a10 10 0 0 1 14 0\" />\n  <path d=\"M8.5 16.429a5 5 0 0 1 7 0\" /></g>"
  },
  {
    "name": "globe",
    "label": "Globe",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接",
      "globe"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20\" />\n  <path d=\"M2 12h20\" /></g>"
  },
  {
    "name": "link",
    "label": "Link",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接",
      "link"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71\" />\n  <path d=\"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71\" /></g>"
  },
  {
    "name": "plug-zap",
    "label": "Plug Zap",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接",
      "plug",
      "zap"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6.3 20.3a2.4 2.4 0 0 0 3.4 0L12 18l-6-6-2.3 2.3a2.4 2.4 0 0 0 0 3.4Z\" />\n  <path d=\"m2 22 3-3\" />\n  <path d=\"M7.5 13.5 10 11\" />\n  <path d=\"M10.5 16.5 13 14\" />\n  <path d=\"m18 3-4 4h6l-4 4\" /></g>"
  },
  {
    "name": "cloud-cog",
    "label": "Cloud Cog",
    "group": "cloud",
    "groupLabel": "云与连接",
    "aliases": [
      "cloud",
      "upload",
      "download",
      "connectivity",
      "云",
      "连接",
      "cog"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m10.852 19.772-.383.924\" />\n  <path d=\"m13.148 14.228.383-.923\" />\n  <path d=\"M13.148 19.772a3 3 0 1 0-2.296-5.544l-.383-.923\" />\n  <path d=\"m13.53 20.696-.382-.924a3 3 0 1 1-2.296-5.544\" />\n  <path d=\"m14.772 15.852.923-.383\" />\n  <path d=\"m14.772 18.148.923.383\" />\n  <path d=\"M4.2 15.1a7 7 0 1 1 9.93-9.858A7 7 0 0 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.2\" />\n  <path d=\"m9.228 15.852-.923-.383\" />\n  <path d=\"m9.228 18.148-.923.383\" /></g>"
  },
  {
    "name": "briefcase",
    "label": "Briefcase",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "briefcase"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16\" />\n  <rect width=\"20\" height=\"14\" x=\"2\" y=\"6\" rx=\"2\" /></g>"
  },
  {
    "name": "building-2",
    "label": "Building 2",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "building",
      "2"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10 12h4\" />\n  <path d=\"M10 8h4\" />\n  <path d=\"M14 21v-3a2 2 0 0 0-4 0v3\" />\n  <path d=\"M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2\" />\n  <path d=\"M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16\" /></g>"
  },
  {
    "name": "factory",
    "label": "Factory",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "factory"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 16h.01\" />\n  <path d=\"M16 16h.01\" />\n  <path d=\"M3 19a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V8.5a.5.5 0 0 0-.769-.422l-4.462 2.844A.5.5 0 0 1 15 10.5v-2a.5.5 0 0 0-.769-.422L9.77 10.922A.5.5 0 0 1 9 10.5V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2z\" />\n  <path d=\"M8 16h.01\" /></g>"
  },
  {
    "name": "store",
    "label": "Store",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "store"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 21v-5a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v5\" />\n  <path d=\"M17.774 10.31a1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.451 0 1.12 1.12 0 0 0-1.548 0 2.5 2.5 0 0 1-3.452 0 1.12 1.12 0 0 0-1.549 0 2.5 2.5 0 0 1-3.77-3.248l2.889-4.184A2 2 0 0 1 7 2h10a2 2 0 0 1 1.653.873l2.895 4.192a2.5 2.5 0 0 1-3.774 3.244\" />\n  <path d=\"M4 10.95V19a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8.05\" /></g>"
  },
  {
    "name": "badge-dollar-sign",
    "label": "Badge Dollar Sign",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "badge",
      "dollar",
      "sign"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" />\n  <path d=\"M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8\" />\n  <path d=\"M12 18V6\" /></g>"
  },
  {
    "name": "wallet",
    "label": "Wallet",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "wallet"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1\" />\n  <path d=\"M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4\" /></g>"
  },
  {
    "name": "credit-card",
    "label": "Credit Card",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "credit",
      "card"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"20\" height=\"14\" x=\"2\" y=\"5\" rx=\"2\" />\n  <line x1=\"2\" x2=\"22\" y1=\"10\" y2=\"10\" /></g>"
  },
  {
    "name": "receipt",
    "label": "Receipt",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "receipt"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 17V7\" />\n  <path d=\"M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8\" />\n  <path d=\"M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z\" /></g>"
  },
  {
    "name": "handshake",
    "label": "Handshake",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "handshake"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m11 17 2 2a1 1 0 1 0 3-3\" />\n  <path d=\"m14 14 2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4\" />\n  <path d=\"m21 3 1 11h-2\" />\n  <path d=\"M3 3 2 14l6.5 6.5a1 1 0 1 0 3-3\" />\n  <path d=\"M3 4h8\" /></g>"
  },
  {
    "name": "chart-spline",
    "label": "Chart Spline",
    "group": "business",
    "groupLabel": "商业组织",
    "aliases": [
      "business",
      "company",
      "finance",
      "strategy",
      "商业",
      "战略",
      "chart",
      "spline"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 3v16a2 2 0 0 0 2 2h16\" />\n  <path d=\"M7 16c.5-2 1.5-7 4-7 2 0 2 3 4 3 2.5 0 4.5-5 5-7\" /></g>"
  },
  {
    "name": "user",
    "label": "User",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2\" />\n  <circle cx=\"12\" cy=\"7\" r=\"4\" /></g>"
  },
  {
    "name": "users-round",
    "label": "Users Round",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "users",
      "round"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 21a8 8 0 0 0-16 0\" />\n  <circle cx=\"10\" cy=\"8\" r=\"5\" />\n  <path d=\"M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3\" /></g>"
  },
  {
    "name": "user-check",
    "label": "User Check",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m16 11 2 2 4-4\" />\n  <path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" />\n  <circle cx=\"9\" cy=\"7\" r=\"4\" /></g>"
  },
  {
    "name": "user-plus",
    "label": "User Plus",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2\" />\n  <circle cx=\"9\" cy=\"7\" r=\"4\" />\n  <line x1=\"19\" x2=\"19\" y1=\"8\" y2=\"14\" />\n  <line x1=\"22\" x2=\"16\" y1=\"11\" y2=\"11\" /></g>"
  },
  {
    "name": "contact",
    "label": "Contact",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "contact"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 2v2\" />\n  <path d=\"M7 21v-2a2 2 0 012-2h6a2 2 0 012 2v2\" />\n  <path d=\"M8 2v2\" />\n  <circle cx=\"12\" cy=\"10\" r=\"3\" />\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" /></g>"
  },
  {
    "name": "hand",
    "label": "Hand",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "hand"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2\" />\n  <path d=\"M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2\" />\n  <path d=\"M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8\" />\n  <path d=\"M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15\" /></g>"
  },
  {
    "name": "contact-round",
    "label": "Contact Round",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "contact",
      "round"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 2v2\" />\n  <path d=\"M17.915 21a6 6 0 10-12 0\" />\n  <path d=\"M8 2v2\" />\n  <circle cx=\"12\" cy=\"11\" r=\"4\" />\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" /></g>"
  },
  {
    "name": "book-user",
    "label": "Book User",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "book"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 13a3 3 0 1 0-6 0\" />\n  <path d=\"M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20\" />\n  <circle cx=\"12\" cy=\"8\" r=\"2\" /></g>"
  },
  {
    "name": "user-round-search",
    "label": "User Round Search",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "round",
      "search"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"10\" cy=\"8\" r=\"5\" />\n  <path d=\"M2 21a8 8 0 0 1 10.434-7.62\" />\n  <circle cx=\"18\" cy=\"18\" r=\"3\" />\n  <path d=\"m22 22-1.9-1.9\" /></g>"
  },
  {
    "name": "accessibility",
    "label": "Accessibility",
    "group": "people",
    "groupLabel": "人物团队",
    "aliases": [
      "people",
      "team",
      "user",
      "culture",
      "人物",
      "团队",
      "文化",
      "accessibility"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"16\" cy=\"4\" r=\"1\" />\n  <path d=\"m18 19 1-7-6 1\" />\n  <path d=\"m5 8 3-3 5.5 3-2.36 3.5\" />\n  <path d=\"M4.24 14.5a5 5 0 0 0 6.88 6\" />\n  <path d=\"M13.76 17.5a5 5 0 0 0-6.88-6\" /></g>"
  },
  {
    "name": "calendar",
    "label": "Calendar",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "calendar"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 2v3\" />\n  <path d=\"M16 2v3\" />\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" />\n  <path d=\"M3 9h18\" /></g>"
  },
  {
    "name": "calendar-check",
    "label": "Calendar Check",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "calendar",
      "check"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 2v3\" />\n  <path d=\"M16 2v3\" />\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" />\n  <path d=\"M3 9h18\" />\n  <path d=\"m9 15 2 2 4-4\" /></g>"
  },
  {
    "name": "calendar-plus",
    "label": "Calendar Plus",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "calendar",
      "plus"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 18h6\" />\n  <path d=\"M16 2v3\" />\n  <path d=\"M19 15v6\" />\n  <path d=\"M21 11.5V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h8.3\" />\n  <path d=\"M3 9h18\" />\n  <path d=\"M8 2v3\" /></g>"
  },
  {
    "name": "clock",
    "label": "Clock",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "clock"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\" />\n  <path d=\"M12 6v6l4 2\" /></g>"
  },
  {
    "name": "timer",
    "label": "Timer",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "timer"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"10\" x2=\"14\" y1=\"2\" y2=\"2\" />\n  <line x1=\"12\" x2=\"15\" y1=\"14\" y2=\"11\" />\n  <circle cx=\"12\" cy=\"14\" r=\"8\" /></g>"
  },
  {
    "name": "hourglass",
    "label": "Hourglass",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "hourglass"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 22h14\" />\n  <path d=\"M5 2h14\" />\n  <path d=\"M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22\" />\n  <path d=\"M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2\" /></g>"
  },
  {
    "name": "bell",
    "label": "Bell",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "bell"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.268 21a2 2 0 0 0 3.464 0\" />\n  <path d=\"M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326\" /></g>"
  },
  {
    "name": "flag",
    "label": "Flag",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "flag"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 22V4a1 1 0 0 1 .4-.8A6 6 0 0 1 8 2c3 0 5 2 7.333 2q2 0 3.067-.8A1 1 0 0 1 20 4v10a1 1 0 0 1-.4.8A6 6 0 0 1 16 16c-3 0-5-2-8-2a6 6 0 0 0-4 1.528\" /></g>"
  },
  {
    "name": "alarm-clock",
    "label": "Alarm Clock",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "alarm",
      "clock"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"13\" r=\"8\" />\n  <path d=\"M12 9v4l2 2\" />\n  <path d=\"M5 3 2 6\" />\n  <path d=\"m22 6-3-3\" />\n  <path d=\"M6.38 18.7 4 21\" />\n  <path d=\"M17.64 18.67 20 21\" /></g>"
  },
  {
    "name": "calendar-clock",
    "label": "Calendar Clock",
    "group": "time",
    "groupLabel": "时间计划",
    "aliases": [
      "time",
      "schedule",
      "plan",
      "deadline",
      "时间",
      "计划",
      "calendar",
      "clock"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 14v2.2l1.6 1\" />\n  <path d=\"M16 2v3\" />\n  <path d=\"M21 7.338V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h2.338\" />\n  <path d=\"M3 9h5.859\" />\n  <path d=\"M8 2v3\" />\n  <circle cx=\"16\" cy=\"16\" r=\"6\" /></g>"
  },
  {
    "name": "image",
    "label": "Image",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" />\n  <circle cx=\"9\" cy=\"9\" r=\"2\" />\n  <path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" /></g>"
  },
  {
    "name": "images",
    "label": "Images",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "images"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16\" />\n  <path d=\"M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2\" />\n  <circle cx=\"13\" cy=\"7\" r=\"1\" fill=\"currentColor\" />\n  <rect x=\"8\" y=\"2\" width=\"14\" height=\"14\" rx=\"2\" /></g>"
  },
  {
    "name": "play",
    "label": "Play",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "play"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z\" /></g>"
  },
  {
    "name": "pause",
    "label": "Pause",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "pause"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"14\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" />\n  <rect x=\"5\" y=\"3\" width=\"5\" height=\"18\" rx=\"1\" /></g>"
  },
  {
    "name": "video",
    "label": "Video",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5\" />\n  <rect x=\"2\" y=\"6\" width=\"14\" height=\"12\" rx=\"2\" /></g>"
  },
  {
    "name": "camera",
    "label": "Camera",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "camera"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\" />\n  <circle cx=\"12\" cy=\"13\" r=\"3\" /></g>"
  },
  {
    "name": "projector",
    "label": "Projector",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "projector"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 7 3 5\" />\n  <path d=\"M9 6V3\" />\n  <path d=\"m13 7 2-2\" />\n  <circle cx=\"9\" cy=\"13\" r=\"3\" />\n  <path d=\"M11.83 12H20a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h2.17\" />\n  <path d=\"M16 16h2\" /></g>"
  },
  {
    "name": "music",
    "label": "Music",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "music"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9 18V5l12-2v13\" />\n  <circle cx=\"6\" cy=\"18\" r=\"3\" />\n  <circle cx=\"18\" cy=\"16\" r=\"3\" /></g>"
  },
  {
    "name": "mic-vocal",
    "label": "Mic Vocal",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "mic",
      "vocal"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m11 7.601-5.994 8.19a1 1 0 0 0 .1 1.298l.817.818a1 1 0 0 0 1.314.087L15.09 12\" />\n  <path d=\"M16.5 21.174C15.5 20.5 14.372 20 13 20c-2.058 0-3.928 2.356-6 2-2.072-.356-2.775-3.369-1.5-4.5\" />\n  <circle cx=\"16\" cy=\"7\" r=\"5\" /></g>"
  },
  {
    "name": "panels-top-left",
    "label": "Panels Top Left",
    "group": "media",
    "groupLabel": "媒体演示",
    "aliases": [
      "media",
      "presentation",
      "video",
      "image",
      "媒体",
      "演示",
      "panels",
      "top",
      "left"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" />\n  <path d=\"M3 9h18\" />\n  <path d=\"M9 21V9\" /></g>"
  },
  {
    "name": "arrow-up",
    "label": "Arrow Up",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "arrow",
      "up"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m5 12 7-7 7 7\" />\n  <path d=\"M12 19V5\" /></g>"
  },
  {
    "name": "arrow-right",
    "label": "Arrow Right",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "arrow",
      "right"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 12h14\" />\n  <path d=\"m12 5 7 7-7 7\" /></g>"
  },
  {
    "name": "arrow-down",
    "label": "Arrow Down",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "arrow",
      "down"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 5v14\" />\n  <path d=\"m19 12-7 7-7-7\" /></g>"
  },
  {
    "name": "arrow-left",
    "label": "Arrow Left",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "arrow",
      "left"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m12 19-7-7 7-7\" />\n  <path d=\"M19 12H5\" /></g>"
  },
  {
    "name": "split",
    "label": "Split",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "split"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M16 3h5v5\" />\n  <path d=\"M8 3H3v5\" />\n  <path d=\"M12 22v-8.3a4 4 0 0 0-1.172-2.872L3 3\" />\n  <path d=\"m15 9 6-6\" /></g>"
  },
  {
    "name": "merge",
    "label": "Merge",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "merge"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m8 6 4-4 4 4\" />\n  <path d=\"M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22\" />\n  <path d=\"m20 22-5-5\" /></g>"
  },
  {
    "name": "rocket",
    "label": "Rocket",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "rocket"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5\" />\n  <path d=\"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09\" />\n  <path d=\"M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z\" />\n  <path d=\"M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05\" /></g>"
  },
  {
    "name": "recycle",
    "label": "Recycle",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "recycle"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5\" />\n  <path d=\"M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12\" />\n  <path d=\"m14 16-3 3 3 3\" />\n  <path d=\"M8.293 13.596 7.196 9.5 3.1 10.598\" />\n  <path d=\"m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843\" />\n  <path d=\"m13.378 9.633 4.096 1.098 1.097-4.096\" /></g>"
  },
  {
    "name": "move-right",
    "label": "Move Right",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "move",
      "right"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 8L22 12L18 16\" />\n  <path d=\"M2 12H22\" /></g>"
  },
  {
    "name": "earth",
    "label": "Earth",
    "group": "direction",
    "groupLabel": "方向与能量",
    "aliases": [
      "direction",
      "movement",
      "energy",
      "change",
      "方向",
      "变化",
      "earth"
    ],
    "viewBox": "0 0 24 24",
    "body": "<g fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21.54 15H17a2 2 0 0 0-2 2v4.54\" />\n  <path d=\"M7 3.34V5a3 3 0 0 0 3 3a2 2 0 0 1 2 2c0 1.1.9 2 2 2a2 2 0 0 0 2-2c0-1.1.9-2 2-2h3.17\" />\n  <path d=\"M11 21.95V18a2 2 0 0 0-2-2a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05\" />\n  <circle cx=\"12\" cy=\"12\" r=\"10\" /></g>"
  }
] as const
